name: bclqc
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.0=anacondar_1
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - alsa-lib=1.2.12=h4ab18f5_0
  - annotated-types=0.7.0=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.40=ha1999f0_7
  - brotli-python=1.1.0=py312h30efb56_1
  - bwidget=1.9.16=h9eba36c_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.33.1=heb4867d_0
  - ca-certificates=2025.12.2=h06a4308_0
  - cairo=1.18.0=hebfffa5_3
  - certifi=2025.11.12=py312h06a4308_0
  - cffi=1.16.0=py312hf06ca03_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - coloredlogs=15.0.1=pyhd8ed1ab_3
  - colormath=3.0.0=py_2
  - curl=8.9.1=h18eb788_0
  - expat=2.6.2=h59595ed_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h7b6447c_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gettext=0.19.8.1=h9b4dc7a_1
  - gfortran_impl_linux-64=11.2.0=h7a446d4_16
  - giflib=5.2.2=h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - gsl=2.7.1=h6e86dc7_1
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=9.0.0=hda332d3_1
  - hpack=4.0.0=pyh9f0ad1d_0
  - htslib=1.20=h5efdd21_2
  - humanfriendly=10.0=pyhd8ed1ab_6
  - humanize=4.10.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=8.0.0=pyha770c72_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - kaleido-core=0.2.1=h3644ca4_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - krb5=1.21.3=h143b758_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=23_linux64_openblas
  - libcblas=3.9.0=23_linux64_openblas
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.9.1=hdb1bdb2_0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=14.1.0=h77fa898_0
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libglib=2.80.3=h315aac3_2
  - libgomp=14.1.0=h77fa898_0
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=23_linux64_openblas
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libpng=1.6.43=h2797004_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.16=hd590300_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - make=4.2.1=h1bed415_1
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py312h98912ed_0
  - mathjax=2.7.7=ha770c72_3
  - mdurl=0.1.2=pyhd8ed1ab_0
  - multiqc=1.23=pyhdfd78af_0
  - ncurses=6.5=h59595ed_0
  - networkx=3.3=pyhd8ed1ab_1
  - nspr=4.35=h27087fc_0
  - nss=3.102=h593d115_0
  - numpy=2.0.0=py312h22e1c76_0
  - openblas=0.3.27=pthreads_h9eca1d5_1
  - openjdk=22.0.1=h8651b0f_1
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.1=h4bc722e_2
  - packaging=24.1=pyhd8ed1ab_0
  - pango=1.54.0=h4c5309f_1
  - pcre2=10.44=hba22ea6_2
  - picard=3.3.0=hdfd78af_0
  - pillow=10.4.0=py312h287a98d_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - plotly=5.22.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyaml-env=1.2.1=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pydantic=2.8.2=pyhd8ed1ab_0
  - pydantic-core=2.20.1=py312hf008fa9_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.12.4=h194c7f8_0_cpython
  - python-kaleido=0.2.1=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pyyaml=6.0.1=py312h98912ed_1
  - r-base=4.4.1=h745b8e0_14
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - rich=13.7.1=pyhd8ed1ab_0
  - rich-click=1.8.3=pyhd8ed1ab_0
  - sed=4.8=h7b6447c_0
  - setuptools=71.0.4=pyhd8ed1ab_0
  - somalier=0.2.19=h0c29559_0
  - spectra=0.0.11=py_1
  - sqlite=3.46.0=h6d4b2fc_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tenacity=8.5.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h3d55465_1
  - tqdm=4.66.4=pyhd8ed1ab_0
  - typeguard=4.3.0=pyhd8ed1ab_1
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - wheel=0.43.0=pyhd8ed1ab_1
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-libxtst=1.2.5=h4bc722e_0
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.3.1=h4ab18f5_1
  - zstandard=0.23.0=py312h3483029_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - contourpy==1.2.1
      - cycler==0.12.1
      - fonttools==4.53.1
      - interop==1.3.2
      - kiwisolver==1.4.5
      - matplotlib==3.9.1
      - pandas==2.2.2
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - seaborn==0.13.2
      - six==1.16.0
      - tzdata==2024.1
