# Panel name aliases: map sampleinfo panel names to config keys
panel_aliases:
  "Comprehensive Heme Panel": heme_comp
  "MPN Screen Panel (JAK2, CALR, MPL)": heme_mpn
  "JAK2": heme_jak2
  "Peripheral Blood Lymphoma Panel": heme_pblp
  "Tumor": pcp_tumor
  "Normal": pcp_normal

pcp_tumor:
  bait_intervals: /mnt/pns/tracks/ucla_mdl_cancer_ngs_v1_merged_baits.hg38.ilist
  target_intervals: /mnt/pns/tracks/ucla_mdl_cancer_ngs_v1_exon_targets.hg38.ilist
  pipeline_version: PCPTNDx-v2.0
  platform: NovaSeq6000
  pass_min_align_pct: 97.0
  fail_min_align_pct: 97.0
  covered: 250
  pass_min_roi_pct: 90
  fail_min_roi_pct: 90
  pass_min_avgcov: 400
  fail_min_avgcov: 400
  pass_min_reads: 66000000
  fail_min_reads: 66000000
  capture: twist
  capture_version: v1.0
pcp_normal:
  bait_intervals: /mnt/pns/tracks/ucla_mdl_cancer_ngs_v1_merged_baits.hg38.ilist
  target_intervals: /mnt/pns/tracks/ucla_mdl_cancer_ngs_v1_exon_targets.hg38.ilist
  pipeline_version: PCPTNDx-v2.0
  platform: NovaSeq6000
  pass_min_align_pct: 98.0
  fail_min_align_pct: 98.0
  covered: 20
  pass_min_roi_pct: 99
  fail_min_roi_pct: 99
  pass_min_avgcov: 200
  fail_min_avgcov: 200
  pass_min_reads: 26000000
  fail_min_reads: 26000000
  capture: twist
  capture_version: v1.0
heme_comp:
  bait_intervals: /mnt/pns/tracks/goal_ucla_heme_221_merged_baits.hg38.ilist
  target_intervals: /mnt/pns/tracks/hemev2_roi.interval_list
  pipeline_version: HemeDx-v2.2.0
  platform: NovaSeq6000
  pass_min_align_pct: 99.0
  fail_min_align_pct: 99.0
  covered: 500
  pass_min_roi_pct: 85
  fail_min_roi_pct: 85
  pass_min_avgcov: 1070
  fail_min_avgcov: 1070
  pass_min_reads: 19000000
  fail_min_reads: 19000000
  capture: goal
  capture_version: v1.0
heme_mpn:
  target_intervals: /mnt/pns/tracks/hemev2_subpanel/MPN.cds10bp.interval_list
heme_jak2:
  target_intervals: /mnt/pns/tracks/hemev2_subpanel/JAK2.cds10bp.interval_list
heme_pblp:
  target_intervals: /mnt/pns/tracks/hemev2_subpanel/PBLP.cds10bp.interval_list
